FROM ubuntu:latest
LABEL maintainer="Liliya233"

ARG TIME_ZONE=Asia/Shanghai

RUN sed -i 's/archive.ubuntu.com/mirrors.bfsu.edu.cn/g' /etc/apt/sources.list \
    && apt-get update -yq \
    && apt-get install ca-certificates -y \
    && apt-get install wget -y \
    && apt-get install tzdata -y \
    && apt-get install default-jdk -y \
    && apt-get install python3 -y \
    && ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo $TIME_ZONE > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && mkdir /workspace

WORKDIR /workspace
